[[pages]]
name = "Data Exploration"
is_section = true
icon = "ğŸ "


[[pages]]
path = "../WebApp/Exploration.py"
name = "Exploration of Event Data"
icon = "ğŸˆï¸"

[[pages]]
path = "../WebApp/HouseData/ExplorationHouse.py"
name = "Exploration of House Data"
icon = "ğŸˆï¸"

[[pages]]
name = "Regression and Classification"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "../WebApp/ClassificationModels.py"
name = "Classification (Event data)"
icon = "ğŸ "

[[pages]]
path = "../WebApp/RFModelpredictions.py"
name = "Regression (Event data)"
icon = ":books:"

[[pages]]
path = "../WebApp/HouseData/RFModelHouse.py"
name = "Regression (House data)"
icon = ":books:"

[[pages]]
name = "Clustering and Neural Networks"
icon = "ğŸˆï¸"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
path = "../WebApp/neuralNetworksModels.py" 
name = "Neural Networks (Event data)"
icon = "ğŸ’ª"

[[pages]]
path = "../WebApp/HouseData/neuralNetworksHouse.py" 
name = "Neural Networks (House data)"
icon = "ğŸ’ª"