[[pages]]
name = "Data Exploration"
is_section = true
icon = "ğŸ "


[[pages]]
path = "../WebApp/Exploration.py"
name = "Exploration of Event Data"
icon = "ğŸˆï¸"


[[pages]]
name = "Regression and Classification"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "../WebApp/ClassificationModels.py"
name = "Classification"
icon = "ğŸ "

[[pages]]
path = "../WebApp/RFModelpredictions.py"
name = "Regression"
icon = ":books:"

[[pages]]
name = "Clustering and Neural Networks"
icon = "ğŸˆï¸"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
path = "../WebApp/neuralNetworksModels.py" 
name = "Neural Networks"
icon = "ğŸ’ª"