[[pages]]
name = "Data Exploration"
is_section = true
icon = "ğŸ "

[[pages]]
path = "Exploration.py"
name = "Exploration of Event Data"
icon = "ğŸˆï¸"

[[pages]]
path = "HouseData/ExplorationHouse.py"
name = "Exploration of House Data"
icon = "ğŸˆï¸"

[[pages]]
name = "Regression and Classification"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "ClassificationModels.py"
name = "Classification (Event data)"
icon = "ğŸ "

[[pages]]
path = "RFModelpredictions.py"
name = "Regression (Event data)"
icon = ":books:"

[[pages]]
path = "HouseData/RFModelHouse.py"
name = "Regression (House data)"
icon = ":books:"

[[pages]]
name = "Clustering and Neural Networks"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "neuralNetworksModels.py"
name = "Neural Networks (Event data)"
icon = "ğŸ’ª"

[[pages]]
path = "HouseData/neuralNetworksHouse.py"
name = "Neural Networks (House data)"
icon = "ğŸ’ª"
